name: Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets._GITHUB_API_KEY }}
  REPO_DIR_NAME: content-id-to-dandiset-paths

jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        run: git clone -b improve https://x-access-token:${{ secrets._GITHUB_API_KEY }}@github.com/dandi-cache/content-id-to-dandiset-paths.git

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Run
        run: |
          pip install s5cmd PyYaml

          cd $REPO_DIR_NAME
          pwd
          ls
          s5cmd --no-sign-request cp "s3://dandiarchive/dandisets/*/assets.yaml" sourcedata || true
          python code/update.py

      - name: Upload
        run: |
          cd $REPO_DIR_NAME
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit --message "update" || true  # || true in case of no changes
          git push

  NotifyOnFailure:
    runs-on: ubuntu-latest
    needs: [ Update ]
    if: ${{ always() && failure() }}
    steps:
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "CI Failure: DANDI Cache: Content ID â†’ Dandiset paths update"
          to: cody.c.baker.phd@gmail.com  # Add more with comma separation (no spaces)
          from: dandi-cache
          body: "Please check the latest run of the BIDS-Dandisets Dashboard update: https://github.com/dandi-cache/content-id-to-dandiset-paths/actions/workflows/update.yml"
